name: Update CSV File

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정(UTC)에 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 환경 설정
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: CSV 파일 업데이트
        run: |
          python update_csv.py

      - name: 변경사항 커밋 및 푸시
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.csv
          git commit -m "자동 업데이트: $(date '+%Y-%m-%d')"
          git push
