name: Update Oil & Exchange Rate Data

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정 실행
  workflow_dispatch:  # 수동 실행 가능

permissions: write-all  # ✅ 저장소에 변경사항을 푸시할 수 있도록 설정

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}  # ✅ GitHub에서 토큰을 사용하도록 설정

      - name: Python 설정
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: 필요 패키지 설치
        run: pip install requests pandas PyGithub python-dotenv

      - name: CSV 파일 업데이트 실행
        env:
          OPINET_API_KEY: ${{ secrets.OPINET_API_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python update_csv.py
